name: rental_room
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.11.0






#---------- PACKAGES -------------#
dependencies:
  flutter:
    sdk: flutter

  # Utilities Packages
  http: ^1.6.0
  intl: ^0.18.0
  logger: ^2.6.2
  url_launcher: ^6.3.2

  # Icons  
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # Statemanagement
  get: ^4.6.5
  get_storage: ^2.1.1


  # Product Specifications

#----------- ./ PACKAGES ENDS ---------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^6.0.0





flutter:
  uses-material-design: true

  #------------- LOCAL ASSETS ---------#
  assets:
    - assets/logos
    - assets/icons
    - assets/images

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
